### PR TITLE
Listen on port 80 when started via systemd.

### PR DESCRIPTION
**Pull request by aylen384**

### CODE REVIEW

**Comment by okurz** [comment]
Can you explain what for? Would this break something?

**Comment by asdil12** [comment]
(@frankenmichl told me it was listening on 8080 in the past due to running on a machine where openQA was listening on port 80, but this not the case anymore)

**Comment by asdil12** [comment]
I already reverse engineered the ipxe script from the existing binaries.
Rebuilding them is no problem for me - actually I just did that for testing.
For now I'm overwriting the port to 80 on the prg2 baremetal-support server.

**Comment by okurz** [comment]
ok, I agree with you but can you please make the reason obvious within the git commit message? Something like "Just use the default port 80 in systemd"

**Comment by asdil12** [comment]
Updated patch.
Also updated systemd override file on baremetal-support.nue2 so that it will listen on both ports for now:

```ini
# /etc/systemd/system/baremetal_support.service.d/override.conf
[Service]
Type=simple
ExecStart=
ExecStartPre=/usr/sbin/iptables -t nat -A PREROUTING -i eth0 -p tcp --dport 8080 -j REDIRECT --to-ports 80
ExecStart=/usr/bin/python3 /opt/baremetal_support/baremetal_support.py -p 80

**Review by frankenmichl — APPROVED** [review]

**Review by okurz — APPROVED** [review]

**Pull request merged**
